/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as MinigameRouteImport } from './routes/minigame'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VrRouteImport } from './routes/vr'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as StudentClassClassCodeRouteImport } from './routes/student.class.$classCode'
import { Route as TeacherAssignmentAssignmentIdRouteImport } from './routes/teacher.assignment.$assignmentId'
import { Route as TeacherClassClassCodeRouteImport } from './routes/teacher.class.$classCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const MinigameRoute = MinigameRouteImport.update({
  id: '/minigame',
  path: '/minigame',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VrRoute = VrRouteImport.update({
  id: '/vr',
  path: '/vr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentClassClassCodeRoute = StudentClassClassCodeRouteImport.update({
  id: '/student/class/$classCode',
  path: '/student/class/$classCode',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignmentAssignmentIdRoute =
  TeacherAssignmentAssignmentIdRouteImport.update({
    id: '/teacher/assignment/$assignmentId',
    path: '/teacher/assignment/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeacherClassClassCodeRoute = TeacherClassClassCodeRouteImport.update({
  id: '/teacher/class/$classCode',
  path: '/teacher/class/$classCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/mentor': typeof MentorRoute
  '/minigame': typeof MinigameRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vr': typeof VrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/class/$classCode': typeof StudentClassClassCodeRoute
  '/teacher/assignment/$assignmentId': typeof TeacherAssignmentAssignmentIdRoute
  '/teacher/class/$classCode': typeof TeacherClassClassCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/mentor': typeof MentorRoute
  '/minigame': typeof MinigameRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vr': typeof VrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/class/$classCode': typeof StudentClassClassCodeRoute
  '/teacher/assignment/$assignmentId': typeof TeacherAssignmentAssignmentIdRoute
  '/teacher/class/$classCode': typeof TeacherClassClassCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contests': typeof ContestsRoute
  '/faq': typeof FaqRoute
  '/journal': typeof JournalRoute
  '/mentor': typeof MentorRoute
  '/minigame': typeof MinigameRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vr': typeof VrRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/student/class/$classCode': typeof StudentClassClassCodeRoute
  '/teacher/assignment/$assignmentId': typeof TeacherAssignmentAssignmentIdRoute
  '/teacher/class/$classCode': typeof TeacherClassClassCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/community'
    | '/contact'
    | '/contests'
    | '/faq'
    | '/journal'
    | '/mentor'
    | '/minigame'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/vr'
    | '/admin/dashboard'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/student/class/$classCode'
    | '/teacher/assignment/$assignmentId'
    | '/teacher/class/$classCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/community'
    | '/contact'
    | '/contests'
    | '/faq'
    | '/journal'
    | '/mentor'
    | '/minigame'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/vr'
    | '/admin/dashboard'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/student/class/$classCode'
    | '/teacher/assignment/$assignmentId'
    | '/teacher/class/$classCode'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/community'
    | '/contact'
    | '/contests'
    | '/faq'
    | '/journal'
    | '/mentor'
    | '/minigame'
    | '/opportunities'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/vr'
    | '/admin/dashboard'
    | '/student/dashboard'
    | '/teacher/dashboard'
    | '/student/class/$classCode'
    | '/teacher/assignment/$assignmentId'
    | '/teacher/class/$classCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ContestsRoute: typeof ContestsRoute
  FaqRoute: typeof FaqRoute
  JournalRoute: typeof JournalRoute
  MentorRoute: typeof MentorRoute
  MinigameRoute: typeof MinigameRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VrRoute: typeof VrRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  StudentClassClassCodeRoute: typeof StudentClassClassCodeRoute
  TeacherAssignmentAssignmentIdRoute: typeof TeacherAssignmentAssignmentIdRoute
  TeacherClassClassCodeRoute: typeof TeacherClassClassCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minigame': {
      id: '/minigame'
      path: '/minigame'
      fullPath: '/minigame'
      preLoaderRoute: typeof MinigameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vr': {
      id: '/vr'
      path: '/vr'
      fullPath: '/vr'
      preLoaderRoute: typeof VrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/class/$classCode': {
      id: '/student/class/$classCode'
      path: '/student/class/$classCode'
      fullPath: '/student/class/$classCode'
      preLoaderRoute: typeof StudentClassClassCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assignment/$assignmentId': {
      id: '/teacher/assignment/$assignmentId'
      path: '/teacher/assignment/$assignmentId'
      fullPath: '/teacher/assignment/$assignmentId'
      preLoaderRoute: typeof TeacherAssignmentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class/$classCode': {
      id: '/teacher/class/$classCode'
      path: '/teacher/class/$classCode'
      fullPath: '/teacher/class/$classCode'
      preLoaderRoute: typeof TeacherClassClassCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ContestsRoute: ContestsRoute,
  FaqRoute: FaqRoute,
  JournalRoute: JournalRoute,
  MentorRoute: MentorRoute,
  MinigameRoute: MinigameRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VrRoute: VrRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  StudentClassClassCodeRoute: StudentClassClassCodeRoute,
  TeacherAssignmentAssignmentIdRoute: TeacherAssignmentAssignmentIdRoute,
  TeacherClassClassCodeRoute: TeacherClassClassCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
